version: "3.9"

services:
  scraper:
    restart: on-failure
    container_name: scraper
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy

  focused_webapp:
    restart: always
    container_name: focused_webapp
    build: ./webapp
    ports: 
      - "4000:4000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - scraper
      - postgres

  selenium:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.selenium
    container_name: selenium-container

  postgres:
    restart: always
    container_name: postgres-container
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

volumes:
  db-data:
