version: "3.9"

services:
  scraper:
    restart: on-failure
    container_name: scraper
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - selenium
      - postgres

  focused_webapp:
    restart: always
    container_name: focused_webapp
    build: ./webapp
    ports: 
      - "4000:4000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    depends_on:
      - scraper
      - postgres

  selenium:
    image: selenium/standalone-chrome:latest  
    container_name: selenium-container

  postgres:
    restart: always
    container_name: postgres-container
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dependencies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"

volumes:
  db-data:
